import esbuild from 'esbuild';
import { copy } from 'esbuild-plugin-copy';
import process from 'process';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';
const outDir = prod ? 'dist' : '../.obsidian/plugins/obsidian-granola';

esbuild.build({
  banner: {
    js: banner,
  },
  entryPoints: ['main.ts'],
  bundle: true,
  external: ['obsidian', 'electron', '@codemirror/state', '@codemirror/view'],
  format: 'cjs',
  target: 'es2020',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: `${outDir}/main.js`,
  plugins: [
    copy({
      assets: [
        { from: ['manifest.json'], to: ['.'] },
        { from: ['styles.css'], to: ['.'], if: ['styles.css'] },
      ],
    }),
  ],
}).catch(() => process.exit(1));
